//! Parity tests: Rust sync_buddy vs Bun sync_real_buddy.ts
//!
//! Fixture generated by: bun scripts/gen_sync_buddy_vectors.ts
//! 1000 vectors: 990 deterministic UUIDs + 10 edge cases.

use pixel_terminal_lib::commands::companion::{derive_voice, roll_bones, wyhash_seed};
use serde::Deserialize;
use std::collections::HashMap;

#[derive(Deserialize)]
struct Vector {
    uuid:  String,
    seed:  u32,
    bones: BonesFix,
    voice: String,
}

#[derive(Deserialize)]
struct BonesFix {
    rarity:  String,
    species: String,
    eyes:    String,
    hat:     String,
    shiny:   bool,
    stats:   HashMap<String, i32>,
}

#[derive(Deserialize)]
struct Fixture {
    vectors: Vec<Vector>,
}

fn load_fixture() -> Fixture {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/sync_buddy_vectors.json"
    );
    let raw = std::fs::read_to_string(path)
        .expect("fixture file missing — run: bun scripts/gen_sync_buddy_vectors.ts");
    serde_json::from_str(&raw).expect("fixture JSON malformed")
}

#[test]
fn test_wyhash_seed_parity() {
    let fix = load_fixture();
    let mut mismatches = 0usize;

    for v in &fix.vectors {
        let got = wyhash_seed(&v.uuid);
        if got != v.seed {
            eprintln!("[SEED MISMATCH] uuid={:?}  expected={}  got={}", v.uuid, v.seed, got);
            mismatches += 1;
        }
    }
    assert_eq!(mismatches, 0, "{} / {} seed mismatches", mismatches, fix.vectors.len());
}

#[test]
fn test_roll_bones_parity() {
    let fix = load_fixture();
    let mut mismatches = 0usize;

    for v in &fix.vectors {
        let bones = roll_bones(&v.uuid);

        let mut ok = true;
        if bones.rarity  != v.bones.rarity  { ok = false; eprintln!("[RARITY]  uuid={:?} expected={} got={}", v.uuid, v.bones.rarity, bones.rarity); }
        if bones.species != v.bones.species  { ok = false; eprintln!("[SPECIES] uuid={:?} expected={} got={}", v.uuid, v.bones.species, bones.species); }
        if bones.eyes    != v.bones.eyes     { ok = false; eprintln!("[EYES]    uuid={:?} expected={} got={}", v.uuid, v.bones.eyes, bones.eyes); }
        if bones.hat     != v.bones.hat      { ok = false; eprintln!("[HAT]     uuid={:?} expected={} got={}", v.uuid, v.bones.hat, bones.hat); }
        if bones.shiny   != v.bones.shiny    { ok = false; eprintln!("[SHINY]   uuid={:?} expected={} got={}", v.uuid, v.bones.shiny, bones.shiny); }

        for stat in &["debugging", "patience", "chaos", "wisdom", "snark"] {
            let exp = v.bones.stats.get(*stat).copied().unwrap_or(0);
            let got = bones.stats.get(*stat).copied().unwrap_or(0);
            if exp != got {
                ok = false;
                eprintln!("[STAT:{}] uuid={:?} expected={} got={}", stat, v.uuid, exp, got);
            }
        }

        if !ok { mismatches += 1; }
    }
    assert_eq!(mismatches, 0, "{} / {} bone mismatches", mismatches, fix.vectors.len());
}

#[test]
fn test_derive_voice_parity() {
    let fix = load_fixture();
    let mut mismatches = 0usize;

    for v in &fix.vectors {
        let bones = roll_bones(&v.uuid);
        let got   = derive_voice(&bones.stats);
        if got != v.voice {
            eprintln!("[VOICE] uuid={:?} expected={} got={}", v.uuid, v.voice, got);
            mismatches += 1;
        }
    }
    assert_eq!(mismatches, 0, "{} / {} voice mismatches", mismatches, fix.vectors.len());
}
